import type { Project } from "./types";

// Translatable fields (description, category, case study text, stats text,
// overview rich text) live in messages/{en,pt-PT}.json under
// projects.items.{slug}. Stats `id` here matches the stat id under
// items.{slug}.stats.{id}.
export const projects: ReadonlyArray<Project> = [
  {
    slug: "chave-movel-digital",
    name: "Chave Móvel Digital",
    startYear: 2022,
    endYear: 2025,
    accent: "blue",
    tags: [".NET", "C#", "REST", "SOAP", "SQL Server"],
    stats: [
      { id: "users" },
      { id: "codebaseAge" },
      { id: "regressions", highlight: true },
      { id: "integrations" },
    ],
    hasCaseStudy: true,
    hasImpact: true,
    liveUrl: "https://www.autenticacao.gov.pt",
    previewImage: "/CMD.png",
  },
  {
    slug: "sam",
    name: "Serviço de Alteração de Morada",
    startYear: 2025,
    endYear: 2025,
    accent: "green",
    tags: [
      "Next.js 15",
      "TypeScript",
      "Tailwind",
      "Jest",
      "Kubernetes",
      "Microcks",
      "Keycloak",
      "SSO",
    ],
    stats: [
      { id: "coverage", highlight: true },
      { id: "team" },
      { id: "stack" },
      { id: "envs" },
    ],
    hasCaseStudy: true,
    hasImpact: true,
  },
  {
    slug: "mavie-decor",
    name: "Mavie Decor",
    startYear: 2026,
    endYear: 2026,
    accent: "orange",
    tags: [
      "Next.js 16",
      "TypeScript",
      "Tailwind 4",
      "Drizzle",
      "Neon",
      "Vercel Blob",
      "GSAP",
    ],
    stats: [
      { id: "lighthouse", highlight: true },
      { id: "tables" },
      { id: "admin" },
      { id: "channel" },
    ],
    hasCaseStudy: true,
    hasImpact: true,
    liveUrl: "https://maviedecor.pt",
    sourceUrl: "https://github.com/devlucasmigueis/mavie-decor-landing",
    previewImage: "/mavie-decor.jpg",
  },
  {
    slug: "eiri-petsitter",
    name: "Eiri Pet Sitter",
    startYear: 2026,
    endYear: 2026,
    accent: "blue",
    tags: [
      "React 19",
      "Vite",
      "TypeScript",
      "Tailwind 4",
      "Sanity",
      "Vitest",
      "Cloudflare Workers",
    ],
    stats: [
      { id: "cms" },
      { id: "fallback", highlight: true },
      { id: "locales" },
      { id: "cost" },
    ],
    hasCaseStudy: true,
    hasImpact: true,
    liveUrl: "https://eiri-petsitter.lucasmigueis1311.workers.dev",
    previewImage: "/eiri-petsitter.jpg",
  },
  {
    slug: "stay-safe",
    name: "Stay Safe",
    startYear: 2020,
    endYear: 2021,
    accent: "amber",
    tags: ["React Native", "Google Maps API"],
    stats: [
      { id: "grade", highlight: true },
      { id: "duration" },
      { id: "scope" },
      { id: "legacy" },
    ],
    hasCaseStudy: true,
    hasImpact: true,
  },
  {
    slug: "lucasmigueis-portfolio",
    name: "Personal Portfolio",
    startYear: 2026,
    endYear: 2026,
    accent: "violet",
    tags: [
      "Next.js 16",
      "TypeScript",
      "Tailwind 4",
      "next-intl",
      "motion",
      "Vercel",
    ],
    stats: [
      { id: "locales" },
      { id: "lighthouse", highlight: true },
      { id: "tokens" },
      { id: "deps" },
    ],
    hasCaseStudy: true,
    hasImpact: true,
    liveUrl: "https://lucasmigueis.com",
    sourceUrl: "https://github.com/devlucasmigueis/lucasmigueis-portfolio",
    previewImage: "/portfolio.png",
  },
];
